In [93]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\olga\anaconda3\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [34]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:0000@localhost:5432/crime_spb"
)

In [35]:
crime_city = pd.read_sql("SELECT * FROM crime_city", engine)
crime_city.head()

,id,report_id,city_name,period_start,period_end,period_type,metric_group,metric_name,metric_code,value,unit,yoy_percent,share_percent,created_at
0,1131,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Общая преступность,Всего преступлений,total_crimes,19214.0,count,None,None,2026-05-05 15:32:14.618195
1,1132,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Тяжкие и особо тяжкие,Всего тяжких и особо тяжких преступлений,serious_total,8555.0,count,None,None,2026-05-05 15:32:14.618195
2,1133,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Экономические преступления,Всего преступлений экономической направленности,econ_total,1922.0,count,None,None,2026-05-05 15:32:14.618195
3,1134,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3216.0,count,None,None,2026-05-05 15:32:14.618195
4,1135,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Преступления против собственности,Всего преступлений против собственности,property_total,660.0,count,None,None,2026-05-05 15:32:14.618195

In [36]:
crime_city.info()
crime_city.describe(include="all").T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             371 non-null    int64
 1   report_id      371 non-null    int64
 2   city_name      371 non-null    object
 3   period_start   371 non-null    object
 4   period_end     371 non-null    object
 5   period_type    371 non-null    object
 6   metric_group   371 non-null    object
 7   metric_name    371 non-null    object
 8   metric_code    371 non-null    object
 9   value          371 non-null    float64
 10  unit           371 non-null    object
 11  yoy_percent    0 non-null      object
 12  share_percent  0 non-null      object
 13  created_at     371 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(10)
memory usage: 40.7+ KB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
id,371.0,NaN,NaN,NaN,1316.0,1131.0,1223.5,1316.0,1408.5,1501.0,107.242715
report_id,371.0,NaN,NaN,NaN,303.0,277.0,290.0,303.0,316.0,329.0,15.317716
city_name,371,1,Санкт-Петербург,371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
period_start,371,6,2021-01-01,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
period_end,371,53,2021-01-31,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
period_type,371,1,month_cum,371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metric_group,371,7,Общая преступность,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metric_name,371,7,Всего преступлений,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metric_code,371,7,total_crimes,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
value,371.0,NaN,NaN,NaN,15593.668464,660.0,3805.5,9050.0,21042.5,81572.0,17293.47102
unit,371,1,count,371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yoy_percent,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
share_percent,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,371,NaN,NaN,NaN,2026-05-05 15:32:14.618194944,2026-05-05 15:32:14.618195,2026-05-05 15:32:14.618194944,2026-05-05 15:32:14.618194944,2026-05-05 15:32:14.618194944,2026-05-05 15:32:14.618195,NaN

In [37]:
crime_city.isna().sum().sort_values(ascending=False)

yoy_percent      371
share_percent    371
id                 0
report_id          0
city_name          0
period_start       0
period_end         0
period_type        0
metric_group       0
metric_name        0
metric_code        0
value              0
unit               0
created_at         0
dtype: int64

In [38]:
crime_city.duplicated().sum()

np.int64(0)

In [39]:
crime_city.duplicated(subset=["city_name", "period_start", "metric_code"]).sum()

np.int64(329)

In [40]:
crime_city = crime_city.drop(columns=["yoy_percent", "share_percent"])

In [41]:
crime_city["period_start"] = pd.to_datetime(crime_city["period_start"])
crime_city["period_end"] = pd.to_datetime(crime_city["period_end"])

In [42]:
crime_city["year"] = crime_city["period_start"].dt.year
crime_city["month"] = crime_city["period_start"].dt.month

In [43]:
f_dups = crime_city.duplicated().sum()
key_dups = crime_city.duplicated(
    subset=["city_name", "period_start", "metric_code"]
).sum()

f_dups, key_dups

(np.int64(0), np.int64(329))

In [44]:
crime_city[["metric_group", "metric_code", "metric_name"]].drop_duplicates().sort_values(
    ["metric_group", "metric_code"]
)

,metric_group,metric_code,metric_name
5,Кражи,theft_total,Всего краж (ст. 158)
3,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо..."
0,Общая преступность,total_crimes,Всего преступлений
4,Преступления против собственности,property_total,Всего преступлений против собственности
6,Раскрываемость,solved_crimes,Всего раскрыто
1,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений
2,Экономические преступления,econ_total,Всего преступлений экономической направленности

In [45]:
dups = crime_city[
    crime_city.duplicated(subset=["city_name", "period_start", "metric_code"], keep=False)
].sort_values(["city_name", "metric_code", "period_start"])
dups.head(20)

,id,report_id,city_name,period_start,period_end,period_type,metric_group,metric_name,metric_code,value,unit,created_at,year,month
3,1134,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3216.0,count,2026-05-05 15:32:14.618195,2021,1
10,1141,278,Санкт-Петербург,2021-01-01,2021-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3828.0,count,2026-05-05 15:32:14.618195,2021,1
17,1148,279,Санкт-Петербург,2021-01-01,2021-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4516.0,count,2026-05-05 15:32:14.618195,2021,1
24,1155,280,Санкт-Петербург,2021-01-01,2021-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5216.0,count,2026-05-05 15:32:14.618195,2021,1
31,1162,281,Санкт-Петербург,2021-01-01,2021-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5944.0,count,2026-05-05 15:32:14.618195,2021,1
38,1169,282,Санкт-Петербург,2021-01-01,2021-06-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6496.0,count,2026-05-05 15:32:14.618195,2021,1
45,1176,283,Санкт-Петербург,2021-01-01,2021-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7166.0,count,2026-05-05 15:32:14.618195,2021,1
52,1183,284,Санкт-Петербург,2021-01-01,2021-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7730.0,count,2026-05-05 15:32:14.618195,2021,1
59,1190,285,Санкт-Петербург,2021-01-01,2021-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8291.0,count,2026-05-05 15:32:14.618195,2021,1
66,1197,286,Санкт-Петербург,2021-01-01,2021-10-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,9106.0,count,2026-05-05 15:32:14.618195,2021,1
73,1204,287,Санкт-Петербург,2021-01-01,2021-11-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,9672.0,count,2026-05-05 15:32:14.618195,2021,1
80,1211,288,Санкт-Петербург,2021-01-01,2021-12-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,10099.0,count,2026-05-05 15:32:14.618195,2021,1
87,1218,289,Санкт-Петербург,2022-01-01,2022-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3082.0,count,2026-05-05 15:32:14.618195,2022,1
94,1225,290,Санкт-Петербург,2022-01-01,2022-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3495.0,count,2026-05-05 15:32:14.618195,2022,1
101,1232,291,Санкт-Петербург,2022-01-01,2022-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4211.0,count,2026-05-05 15:32:14.618195,2022,1
109,1239,292,Санкт-Петербург,2022-01-01,2022-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4772.0,count,2026-05-05 15:32:14.618195,2022,1
116,1246,293,Санкт-Петербург,2022-01-01,2022-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5260.0,count,2026-05-05 15:32:14.618195,2022,1
123,1253,294,Санкт-Петербург,2022-01-01,2022-06-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5821.0,count,2026-05-05 15:32:14.618195,2022,1
130,1260,295,Санкт-Петербург,2022-01-01,2022-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6460.0,count,2026-05-05 15:32:14.618195,2022,1
138,1267,296,Санкт-Петербург,2022-01-01,2022-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6900.0,count,2026-05-05 15:32:14.618195,2022,1

In [46]:
year_end = crime_city[crime_city["period_end"].dt.month == 12].copy()
crime_yearly = (
    year_end
    .sort_values("period_end")
    .groupby(["city_name", "year", "metric_group", "metric_code", "metric_name"], as_index=False)
    .agg({"value": "last"})
)

crime_yearly.head()

,city_name,year,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021,Кражи,theft_total,Всего краж (ст. 158),27032.0
1,Санкт-Петербург,2021,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",10099.0
2,Санкт-Петербург,2021,Общая преступность,total_crimes,Всего преступлений,76966.0
3,Санкт-Петербург,2021,Преступления против собственности,property_total,Всего преступлений против собственности,1282.0
4,Санкт-Петербург,2021,Раскрываемость,solved_crimes,Всего раскрыто,25613.0

In [47]:
crime_city_sorted = crime_city.sort_values(["city_name", "metric_code", "period_end"])

crime_monthly = crime_city_sorted.copy()

crime_monthly["monthly_value"] = (
    crime_city_sorted
    .groupby(["city_name", "metric_code", "year"])["value"]
    .diff()
    .fillna(crime_city_sorted["value"])
)

crime_monthly.head()

,id,report_id,city_name,period_start,period_end,period_type,metric_group,metric_name,metric_code,value,unit,created_at,year,month,monthly_value
3,1134,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3216.0,count,2026-05-05 15:32:14.618195,2021,1,3216.0
10,1141,278,Санкт-Петербург,2021-01-01,2021-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3828.0,count,2026-05-05 15:32:14.618195,2021,1,612.0
17,1148,279,Санкт-Петербург,2021-01-01,2021-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4516.0,count,2026-05-05 15:32:14.618195,2021,1,688.0
24,1155,280,Санкт-Петербург,2021-01-01,2021-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5216.0,count,2026-05-05 15:32:14.618195,2021,1,700.0
31,1162,281,Санкт-Петербург,2021-01-01,2021-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5944.0,count,2026-05-05 15:32:14.618195,2021,1,728.0

In [48]:
crime_city.dtypes

id                       int64
report_id                int64
city_name               object
period_start    datetime64[ns]
period_end      datetime64[ns]
period_type             object
metric_group            object
metric_name             object
metric_code             object
value                  float64
unit                    object
created_at      datetime64[ns]
year                     int32
month                    int32
dtype: object

In [49]:
crime_city.head(3)

,id,report_id,city_name,period_start,period_end,period_type,metric_group,metric_name,metric_code,value,unit,created_at,year,month
0,1131,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Общая преступность,Всего преступлений,total_crimes,19214.0,count,2026-05-05 15:32:14.618195,2021,1
1,1132,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Тяжкие и особо тяжкие,Всего тяжких и особо тяжких преступлений,serious_total,8555.0,count,2026-05-05 15:32:14.618195,2021,1
2,1133,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Экономические преступления,Всего преступлений экономической направленности,econ_total,1922.0,count,2026-05-05 15:32:14.618195,2021,1

In [16]:
crime_clean = crime_city.copy()

crime_clean["period_start"] = pd.to_datetime(crime_clean["period_start"])
crime_clean["period_end"]   = pd.to_datetime(crime_clean["period_end"])

crime_clean["year"]  = crime_clean["period_start"].dt.year
crime_clean["month"] = crime_clean["period_end"].dt.month

crime_clean = crime_clean[[
    "city_name",
    "period_start",
    "period_end",
    "year",
    "month",
    "metric_group",
    "metric_code",
    "metric_name",
    "value"
]].copy()

In [17]:
print(crime_clean["month"].unique())
print(
    crime_clean
    .groupby(["metric_code", "year"])["month"]
    .nunique()
    .sort_values()
    .head(20)
)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
metric_code     year
total_crimes    2026     1
solved_crimes   2026     1
serious_total   2026     1
drugs_total     2026     1
theft_total     2026     1
property_total  2026     1
econ_total      2026     1
serious_total   2025     5
drugs_total     2025     5
total_crimes    2025     5
econ_total      2025     5
theft_total     2025     5
solved_crimes   2025     5
property_total  2025     5
serious_total   2024    11
theft_total     2024    11
econ_total      2024    11
drugs_total     2024    11
total_crimes    2024    11
property_total  2024    11
Name: month, dtype: int64

In [18]:
crime_clean.shape
crime_clean["month"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [19]:
crime_clean_sorted = crime_clean.sort_values(
    ["city_name", "metric_code", "year", "period_end"]
)

crime_monthly = crime_clean_sorted.copy()

crime_monthly["monthly_value"] = (
    crime_clean_sorted
    .groupby(["city_name", "metric_code", "year"])["value"]
    .diff()
    .fillna(crime_clean_sorted["value"])
)

In [20]:
year_end = crime_clean[crime_clean["period_end"].dt.month == 12].copy()

crime_yearly = (
    year_end
    .sort_values("period_end")
    .groupby(
        ["city_name", "year", "metric_group", "metric_code", "metric_name"],
        as_index=False
    )
    .agg({"value": "last"})
)

In [21]:
print(crime_clean["month"].unique())
print(crime_clean.shape)

print(crime_monthly.head())
print(crime_yearly["year"].unique())
crime_yearly.head()

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(371, 9)
          city_name period_start period_end  year  month       metric_group  \
3   Санкт-Петербург   2021-01-01 2021-01-31  2021      1  Наркопреступления
10  Санкт-Петербург   2021-01-01 2021-02-28  2021      2  Наркопреступления
17  Санкт-Петербург   2021-01-01 2021-03-31  2021      3  Наркопреступления
24  Санкт-Петербург   2021-01-01 2021-04-30  2021      4  Наркопреступления
31  Санкт-Петербург   2021-01-01 2021-05-31  2021      5  Наркопреступления

    metric_code                                        metric_name   value  \
3   drugs_total  Всего преступлений, связанных с незаконным обо...  3216.0
10  drugs_total  Всего преступлений, связанных с незаконным обо...  3828.0
17  drugs_total  Всего преступлений, связанных с незаконным обо...  4516.0
24  drugs_total  Всего преступлений, связанных с незаконным обо...  5216.0
31  drugs_total  Всего преступлений, связанных с незаконным обо...  5944.0

    monthly_value
3          3216.0
10          612.0
17          688.0
24          700.0
31          728.0
[2021 2022 2023 2024]

,city_name,year,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021,Кражи,theft_total,Всего краж (ст. 158),27032.0
1,Санкт-Петербург,2021,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",10099.0
2,Санкт-Петербург,2021,Общая преступность,total_crimes,Всего преступлений,76966.0
3,Санкт-Петербург,2021,Преступления против собственности,property_total,Всего преступлений против собственности,1282.0
4,Санкт-Петербург,2021,Раскрываемость,solved_crimes,Всего раскрыто,25613.0

In [116]:
print("crime_clean.shape:", crime_clean.shape)
print(crime_clean.dtypes)

print("\nПропуски по колонкам crime_clean:")
print(crime_clean.isna().sum())

crime_clean.shape: (371, 9)
city_name               object
period_start    datetime64[ns]
period_end      datetime64[ns]
year                     int32
month                    int32
metric_group            object
metric_code             object
metric_name             object
value                  float64
dtype: object

Пропуски по колонкам crime_clean:
city_name       0
period_start    0
period_end      0
year            0
month           0
metric_group    0
metric_code     0
metric_name     0
value           0
dtype: int64

In [50]:
print("Полных дубликатов строк:", crime_clean.duplicated().sum())

print(
    "Дубликатов (city_name, metric_code, year, period_end):",
    crime_clean.duplicated(
        subset=["city_name", "metric_code", "year", "period_end"]
    ).sum()
)

Полных дубликатов строк: 0
Дубликатов (city_name, metric_code, year, period_end): 0

In [51]:
print("Уникальные месяцы:", sorted(crime_clean["month"].unique()))
print("Уникальные годы:", sorted(crime_clean["year"].unique()))

months_per_year = (
    crime_clean
    .groupby(["metric_code", "year"])["month"]
    .nunique()
    .reset_index(name="n_months")
)

print("\nСколько месяцев есть по каждой метрике:")
print(
    months_per_year
    .sort_values("n_months")
    .head(20)
)

Уникальные месяцы: [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12)]
Уникальные годы: [np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024), np.int32(2025), np.int32(2026)]

Сколько месяцев есть по каждой метрике:
       metric_code  year  n_months
41    total_crimes  2026         1
29   solved_crimes  2026         1
23   serious_total  2026         1
5      drugs_total  2026         1
35     theft_total  2026         1
17  property_total  2026         1
11      econ_total  2026         1
22   serious_total  2025         5
4      drugs_total  2025         5
40    total_crimes  2025         5
10      econ_total  2025         5
34     theft_total  2025         5
28   solved_crimes  2025         5
16  property_total  2025         5
21   serious_total  2024        11
33     theft_total  2024        11
9       econ_total  2024        11
3      drugs_total  2024        11
39    total_crimes  2024        11
15  property_total  2024        11

In [52]:
neg_cum = crime_clean[crime_clean["value"] < 0]
neg_monthly = crime_monthly[crime_monthly["monthly_value"] < 0]

print("Отрицательные значения в crime_clean:", neg_cum.shape[0])
print("Отрицательных значения в crime_monthly:", neg_monthly.shape[0])

Отрицательные значения в crime_clean: 0
Отрицательных значения в crime_monthly: 10

In [53]:
print("Годы в crime_yearly:", sorted(crime_yearly["year"].unique()))
crime_yearly.head(10)

Годы в crime_yearly: [np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024)]

,city_name,year,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021,Кражи,theft_total,Всего краж (ст. 158),27032.0
1,Санкт-Петербург,2021,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",10099.0
2,Санкт-Петербург,2021,Общая преступность,total_crimes,Всего преступлений,76966.0
3,Санкт-Петербург,2021,Преступления против собственности,property_total,Всего преступлений против собственности,1282.0
4,Санкт-Петербург,2021,Раскрываемость,solved_crimes,Всего раскрыто,25613.0
5,Санкт-Петербург,2021,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,28078.0
6,Санкт-Петербург,2021,Экономические преступления,econ_total,Всего преступлений экономической направленности,4321.0
7,Санкт-Петербург,2022,Кражи,theft_total,Всего краж (ст. 158),27227.0
8,Санкт-Петербург,2022,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",8905.0
9,Санкт-Петербург,2022,Общая преступность,total_crimes,Всего преступлений,76445.0

In [54]:
mask_total = crime_clean["metric_code"] == "total_crimes"
print("\nСтатистика по total_crimes (накопительные):")
print(crime_clean[mask_total]["value"].describe())

mask_total_m = crime_monthly["metric_code"] == "total_crimes"
print("\nСтатистика по total_crimes (помесячные):")
print(crime_monthly[mask_total_m]["monthly_value"].describe())

Статистика по total_crimes (накопительные):
count       53.000000
mean     49851.867925
std      18277.241771
min      19147.000000
25%      35379.000000
50%      51403.000000
75%      65644.000000
max      81572.000000
Name: value, dtype: float64

Статистика по total_crimes (помесячные):
count       53.000000
mean      8108.471698
std       9051.996326
min       3737.000000
25%       5051.000000
50%       5431.000000
75%       5816.000000
max      51499.000000
Name: monthly_value, dtype: float64

In [55]:
print("Годы в crime_yearly:", sorted(crime_yearly["year"].unique()))
crime_yearly.head(10)

Годы в crime_yearly: [np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024)]

,city_name,year,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021,Кражи,theft_total,Всего краж (ст. 158),27032.0
1,Санкт-Петербург,2021,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",10099.0
2,Санкт-Петербург,2021,Общая преступность,total_crimes,Всего преступлений,76966.0
3,Санкт-Петербург,2021,Преступления против собственности,property_total,Всего преступлений против собственности,1282.0
4,Санкт-Петербург,2021,Раскрываемость,solved_crimes,Всего раскрыто,25613.0
5,Санкт-Петербург,2021,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,28078.0
6,Санкт-Петербург,2021,Экономические преступления,econ_total,Всего преступлений экономической направленности,4321.0
7,Санкт-Петербург,2022,Кражи,theft_total,Всего краж (ст. 158),27227.0
8,Санкт-Петербург,2022,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",8905.0
9,Санкт-Петербург,2022,Общая преступность,total_crimes,Всего преступлений,76445.0

In [56]:
kpi_codes = [
    "total_crimes",
    "serious_total",
    "econ_total",
    "theft_total",
    "property_total",
    "drugs_total",
    "solved_crimes",
]

yearly_pivot = (
    crime_yearly[crime_yearly["metric_code"].isin(kpi_codes)]
    .pivot_table(
        index="year",
        columns="metric_code",
        values="value"
    )
    .reset_index()
)

yearly_pivot

metric_code,year,drugs_total,econ_total,property_total,serious_total,solved_crimes,theft_total,total_crimes
0,2021,10099.0,4321.0,1282.0,28078.0,25613.0,27032.0,76966.0
1,2022,8905.0,4373.0,1353.0,24683.0,26190.0,27227.0,76445.0
2,2023,8933.0,4511.0,1377.0,26786.0,27474.0,25406.0,81572.0
3,2024,8201.0,4868.0,1581.0,28827.0,24584.0,21520.0,78723.0

In [57]:
clean_kpi = crime_clean[crime_clean["metric_code"].isin(kpi_codes)]

clean_kpi.head()

,city_name,period_start,period_end,year,month,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Общая преступность,total_crimes,Всего преступлений,19214.0
1,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,8555.0
2,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Экономические преступления,econ_total,Всего преступлений экономической направленности,1922.0
3,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",3216.0
4,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Преступления против собственности,property_total,Всего преступлений против собственности,660.0

In [58]:
kpi_codes = [
    "total_crimes",
    "serious_total",
    "econ_total",
    "theft_total",
    "property_total",
    "drugs_total",
    "solved_crimes",
]

clean_kpi = crime_clean[crime_clean["metric_code"].isin(kpi_codes)]

clean_kpi.head()

,city_name,period_start,period_end,year,month,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Общая преступность,total_crimes,Всего преступлений,19214.0
1,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,8555.0
2,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Экономические преступления,econ_total,Всего преступлений экономической направленности,1922.0
3,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",3216.0
4,Санкт-Петербург,2021-01-01,2021-01-31,2021,1,Преступления против собственности,property_total,Всего преступлений против собственности,660.0

In [59]:
monthly_kpi = crime_monthly[crime_monthly["metric_code"].isin(kpi_codes)]

monthly_kpi.head(50)

,id,report_id,city_name,period_start,period_end,period_type,metric_group,metric_name,metric_code,value,unit,created_at,year,month,monthly_value
3,1134,277,Санкт-Петербург,2021-01-01,2021-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3216.0,count,2026-05-05 15:32:14.618195,2021,1,3216.0
10,1141,278,Санкт-Петербург,2021-01-01,2021-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3828.0,count,2026-05-05 15:32:14.618195,2021,1,612.0
17,1148,279,Санкт-Петербург,2021-01-01,2021-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4516.0,count,2026-05-05 15:32:14.618195,2021,1,688.0
24,1155,280,Санкт-Петербург,2021-01-01,2021-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5216.0,count,2026-05-05 15:32:14.618195,2021,1,700.0
31,1162,281,Санкт-Петербург,2021-01-01,2021-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5944.0,count,2026-05-05 15:32:14.618195,2021,1,728.0
38,1169,282,Санкт-Петербург,2021-01-01,2021-06-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6496.0,count,2026-05-05 15:32:14.618195,2021,1,552.0
45,1176,283,Санкт-Петербург,2021-01-01,2021-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7166.0,count,2026-05-05 15:32:14.618195,2021,1,670.0
52,1183,284,Санкт-Петербург,2021-01-01,2021-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7730.0,count,2026-05-05 15:32:14.618195,2021,1,564.0
59,1190,285,Санкт-Петербург,2021-01-01,2021-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8291.0,count,2026-05-05 15:32:14.618195,2021,1,561.0
66,1197,286,Санкт-Петербург,2021-01-01,2021-10-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,9106.0,count,2026-05-05 15:32:14.618195,2021,1,815.0
73,1204,287,Санкт-Петербург,2021-01-01,2021-11-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,9672.0,count,2026-05-05 15:32:14.618195,2021,1,566.0
80,1211,288,Санкт-Петербург,2021-01-01,2021-12-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,10099.0,count,2026-05-05 15:32:14.618195,2021,1,427.0
87,1218,289,Санкт-Петербург,2022-01-01,2022-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3082.0,count,2026-05-05 15:32:14.618195,2022,1,3082.0
94,1225,290,Санкт-Петербург,2022-01-01,2022-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3495.0,count,2026-05-05 15:32:14.618195,2022,1,413.0
101,1232,291,Санкт-Петербург,2022-01-01,2022-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4211.0,count,2026-05-05 15:32:14.618195,2022,1,716.0
109,1239,292,Санкт-Петербург,2022-01-01,2022-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4772.0,count,2026-05-05 15:32:14.618195,2022,1,561.0
116,1246,293,Санкт-Петербург,2022-01-01,2022-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5260.0,count,2026-05-05 15:32:14.618195,2022,1,488.0
123,1253,294,Санкт-Петербург,2022-01-01,2022-06-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5821.0,count,2026-05-05 15:32:14.618195,2022,1,561.0
130,1260,295,Санкт-Петербург,2022-01-01,2022-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6460.0,count,2026-05-05 15:32:14.618195,2022,1,639.0
138,1267,296,Санкт-Петербург,2022-01-01,2022-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6900.0,count,2026-05-05 15:32:14.618195,2022,1,440.0
145,1274,297,Санкт-Петербург,2022-01-01,2022-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7389.0,count,2026-05-05 15:32:14.618195,2022,1,489.0
152,1281,298,Санкт-Петербург,2022-01-01,2022-10-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8005.0,count,2026-05-05 15:32:14.618195,2022,1,616.0
159,1288,299,Санкт-Петербург,2022-01-01,2022-11-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8571.0,count,2026-05-05 15:32:14.618195,2022,1,566.0
166,1295,300,Санкт-Петербург,2022-01-01,2022-12-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8905.0,count,2026-05-05 15:32:14.618195,2022,1,334.0
174,1302,301,Санкт-Петербург,2023-01-01,2023-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,2810.0,count,2026-05-05 15:32:14.618195,2023,1,2810.0
181,1309,302,Санкт-Петербург,2023-01-01,2023-02-28,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3313.0,count,2026-05-05 15:32:14.618195,2023,1,503.0
188,1316,303,Санкт-Петербург,2023-01-01,2023-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3897.0,count,2026-05-05 15:32:14.618195,2023,1,584.0
195,1323,304,Санкт-Петербург,2023-01-01,2023-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4427.0,count,2026-05-05 15:32:14.618195,2023,1,530.0
202,1330,305,Санкт-Петербург,2023-01-01,2023-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4964.0,count,2026-05-05 15:32:14.618195,2023,1,537.0
209,1337,306,Санкт-Петербург,2023-01-01,2023-06-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5413.0,count,2026-05-05 15:32:14.618195,2023,1,449.0
216,1344,307,Санкт-Петербург,2023-01-01,2023-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5865.0,count,2026-05-05 15:32:14.618195,2023,1,452.0
223,1351,308,Санкт-Петербург,2023-01-01,2023-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6545.0,count,2026-05-05 15:32:14.618195,2023,1,680.0
230,1358,309,Санкт-Петербург,2023-01-01,2023-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7024.0,count,2026-05-05 15:32:14.618195,2023,1,479.0
237,1365,310,Санкт-Петербург,2023-01-01,2023-10-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7710.0,count,2026-05-05 15:32:14.618195,2023,1,686.0
243,1372,311,Санкт-Петербург,2023-01-01,2023-11-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8361.0,count,2026-05-05 15:32:14.618195,2023,1,651.0
250,1379,312,Санкт-Петербург,2023-01-01,2023-12-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8933.0,count,2026-05-05 15:32:14.618195,2023,1,572.0
257,1386,313,Санкт-Петербург,2024-01-01,2024-01-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,2589.0,count,2026-05-05 15:32:14.618195,2024,1,2589.0
264,1393,314,Санкт-Петербург,2024-01-01,2024-02-29,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3024.0,count,2026-05-05 15:32:14.618195,2024,1,435.0
271,1400,315,Санкт-Петербург,2024-01-01,2024-03-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3455.0,count,2026-05-05 15:32:14.618195,2024,1,431.0
277,1407,316,Санкт-Петербург,2024-01-01,2024-04-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,3876.0,count,2026-05-05 15:32:14.618195,2024,1,421.0
284,1414,317,Санкт-Петербург,2024-01-01,2024-05-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,4339.0,count,2026-05-05 15:32:14.618195,2024,1,463.0
291,1421,318,Санкт-Петербург,2024-01-01,2024-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5494.0,count,2026-05-05 15:32:14.618195,2024,1,1155.0
298,1428,319,Санкт-Петербург,2024-01-01,2024-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6221.0,count,2026-05-05 15:32:14.618195,2024,1,727.0
305,1435,320,Санкт-Петербург,2024-01-01,2024-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6762.0,count,2026-05-05 15:32:14.618195,2024,1,541.0
312,1442,321,Санкт-Петербург,2024-01-01,2024-10-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7497.0,count,2026-05-05 15:32:14.618195,2024,1,735.0
319,1449,322,Санкт-Петербург,2024-01-01,2024-11-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,7998.0,count,2026-05-05 15:32:14.618195,2024,1,501.0
326,1456,323,Санкт-Петербург,2024-01-01,2024-12-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,8201.0,count,2026-05-05 15:32:14.618195,2024,1,203.0
333,1463,324,Санкт-Петербург,2025-01-01,2025-07-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,5742.0,count,2026-05-05 15:32:14.618195,2025,1,5742.0
340,1470,325,Санкт-Петербург,2025-01-01,2025-08-31,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6284.0,count,2026-05-05 15:32:14.618195,2025,1,542.0
346,1477,326,Санкт-Петербург,2025-01-01,2025-09-30,month_cum,Наркопреступления,"Всего преступлений, связанных с незаконным обо...",drugs_total,6774.0,count,2026-05-05 15:32:14.618195,2025,1,490.0

In [60]:
print("-crime_clean-")
crime_clean.info()
print()

print("-crime_monthly-")
crime_monthly.info()
print()

print("-crime_yearly-")
crime_yearly.info()

-crime_clean-
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city_name     371 non-null    object
 1   period_start  371 non-null    datetime64[ns]
 2   period_end    371 non-null    datetime64[ns]
 3   year          371 non-null    int32
 4   month         371 non-null    int32
 5   metric_group  371 non-null    object
 6   metric_code   371 non-null    object
 7   metric_name   371 non-null    object
 8   value         371 non-null    float64
dtypes: datetime64[ns](2), float64(1), int32(2), object(4)
memory usage: 23.3+ KB

-crime_monthly-
<class 'pandas.core.frame.DataFrame'>
Index: 371 entries, 3 to 364
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             371 non-null    int64
 1   report_id      371 non-null    int64
 2   city_name      371 non-null    object
 3   period_start   371 non-null    datetime64[ns]
 4   period_end     371 non-null    datetime64[ns]
 5   period_type    371 non-null    object
 6   metric_group   371 non-null    object
 7   metric_name    371 non-null    object
 8   metric_code    371 non-null    object
 9   value          371 non-null    float64
 10  unit           371 non-null    object
 11  created_at     371 non-null    datetime64[ns]
 12  year           371 non-null    int32
 13  month          371 non-null    int32
 14  monthly_value  371 non-null    float64
dtypes: datetime64[ns](3), float64(2), int32(2), int64(2), object(6)
memory usage: 43.5+ KB

-crime_yearly-
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city_name     28 non-null     object
 1   year          28 non-null     int32
 2   metric_group  28 non-null     object
 3   metric_code   28 non-null     object
 4   metric_name   28 non-null     object
 5   value         28 non-null     float64
dtypes: float64(1), int32(1), object(4)
memory usage: 1.3+ KB

In [131]:
crime_clean.to_sql(
    "crime_clean_vitrina",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False
)

crime_monthly.to_sql(
    "crime_monthly_vitrina",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False
)

crime_yearly.to_sql(
    "crime_yearly_vitrina",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False
)

28

In [32]:
import pandas as pd

df_yearly = pd.read_sql("SELECT * FROM crime_yearly_vitrina;", con=engine)
df_yearly.head(30)

,city_name,year,metric_group,metric_code,metric_name,value
0,Санкт-Петербург,2021,Кражи,theft_total,Всего краж (ст. 158),27032.0
1,Санкт-Петербург,2021,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",10099.0
2,Санкт-Петербург,2021,Общая преступность,total_crimes,Всего преступлений,76966.0
3,Санкт-Петербург,2021,Преступления против собственности,property_total,Всего преступлений против собственности,1282.0
4,Санкт-Петербург,2021,Раскрываемость,solved_crimes,Всего раскрыто,25613.0
5,Санкт-Петербург,2021,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,28078.0
6,Санкт-Петербург,2021,Экономические преступления,econ_total,Всего преступлений экономической направленности,4321.0
7,Санкт-Петербург,2022,Кражи,theft_total,Всего краж (ст. 158),27227.0
8,Санкт-Петербург,2022,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",8905.0
9,Санкт-Петербург,2022,Общая преступность,total_crimes,Всего преступлений,76445.0
10,Санкт-Петербург,2022,Преступления против собственности,property_total,Всего преступлений против собственности,1353.0
11,Санкт-Петербург,2022,Раскрываемость,solved_crimes,Всего раскрыто,26190.0
12,Санкт-Петербург,2022,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,24683.0
13,Санкт-Петербург,2022,Экономические преступления,econ_total,Всего преступлений экономической направленности,4373.0
14,Санкт-Петербург,2023,Кражи,theft_total,Всего краж (ст. 158),25406.0
15,Санкт-Петербург,2023,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",8933.0
16,Санкт-Петербург,2023,Общая преступность,total_crimes,Всего преступлений,81572.0
17,Санкт-Петербург,2023,Преступления против собственности,property_total,Всего преступлений против собственности,1377.0
18,Санкт-Петербург,2023,Раскрываемость,solved_crimes,Всего раскрыто,27474.0
19,Санкт-Петербург,2023,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,26786.0
20,Санкт-Петербург,2023,Экономические преступления,econ_total,Всего преступлений экономической направленности,4511.0
21,Санкт-Петербург,2024,Кражи,theft_total,Всего краж (ст. 158),21520.0
22,Санкт-Петербург,2024,Наркопреступления,drugs_total,"Всего преступлений, связанных с незаконным обо...",8201.0
23,Санкт-Петербург,2024,Общая преступность,total_crimes,Всего преступлений,78723.0
24,Санкт-Петербург,2024,Преступления против собственности,property_total,Всего преступлений против собственности,1581.0
25,Санкт-Петербург,2024,Раскрываемость,solved_crimes,Всего раскрыто,24584.0
26,Санкт-Петербург,2024,Тяжкие и особо тяжкие,serious_total,Всего тяжких и особо тяжких преступлений,28827.0
27,Санкт-Петербург,2024,Экономические преступления,econ_total,Всего преступлений экономической направленности,4868.0

In [61]:
crime_clean.to_sql("crime_clean_vitrina", con=engine, schema="public", if_exists="replace", index=False)
crime_monthly.to_sql("crime_monthly_vitrina", con=engine, schema="public", if_exists="replace", index=False)
crime_yearly.to_sql("crime_yearly_vitrina", con=engine, schema="public", if_exists="replace", index=False)

28