In [2]:
import os
import sys

project_root = r"C:\Users\Olga\Диплом\Мой проект"
src_path = os.path.join(project_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print(sys.path[-3:])

['C:\\Users\\Olga\\anaconda3\\Lib\\site-packages\\win32\\lib', 'C:\\Users\\Olga\\anaconda3\\Lib\\site-packages\\Pythonwin', 'C:\\Users\\Olga\\Диплом\\Мой проект\\src']

In [3]:
import pandas as pd
from sqlalchemy import text
from data_loader import get_engine

In [4]:
engine = get_engine()

In [5]:
query = """
    SELECT
        year,
        month,
        metric_code,
        value,
        monthly_value
    FROM crime_spb2
    WHERE year = 2025
      AND month <= 7
    ORDER BY metric_code, month
"""

crime_2025 = pd.read_sql(query, con=engine)
crime_2025

    year  month     metric_code value  monthly_value
0   2025      1     drugs_total  None     820.285714
1   2025      2     drugs_total  None     820.285714
2   2025      3     drugs_total  None     820.285714
3   2025      4     drugs_total  None     820.285714
4   2025      5     drugs_total  None     820.285714
5   2025      6     drugs_total  None     820.285714
6   2025      7     drugs_total  None     820.285714
7   2025      1      econ_total  None     508.714286
8   2025      2      econ_total  None     508.714286
9   2025      3      econ_total  None     508.714286
10  2025      4      econ_total  None     508.714286
11  2025      5      econ_total  None     508.714286
12  2025      6      econ_total  None     508.714286
13  2025      7      econ_total  None     508.714286
14  2025      1  property_total  None     147.000000
15  2025      2  property_total  None     147.000000
16  2025      3  property_total  None     147.000000
17  2025      4  property_total  None     147.000000
18  2025      5  property_total  None     147.000000
19  2025      6  property_total  None     147.000000
20  2025      7  property_total  None     147.000000
21  2025      1   serious_total  None    2835.714286
22  2025      2   serious_total  None    2835.714286
23  2025      3   serious_total  None    2835.714286
24  2025      4   serious_total  None    2835.714286
25  2025      5   serious_total  None    2835.714286
26  2025      6   serious_total  None    2835.714286
27  2025      7   serious_total  None    2835.714286
28  2025      1   solved_crimes  None    2425.428571
29  2025      2   solved_crimes  None    2425.428571
30  2025      3   solved_crimes  None    2425.428571
31  2025      4   solved_crimes  None    2425.428571
32  2025      5   solved_crimes  None    2425.428571
33  2025      6   solved_crimes  None    2425.428571
34  2025      7   solved_crimes  None    2425.428571
35  2025      1     theft_total  None    1828.428571
36  2025      2     theft_total  None    1828.428571
37  2025      3     theft_total  None    1828.428571
38  2025      4     theft_total  None    1828.428571
39  2025      5     theft_total  None    1828.428571
40  2025      6     theft_total  None    1828.428571
41  2025      7     theft_total  None    1828.428571
42  2025      1    total_crimes  None    7357.000000
43  2025      2    total_crimes  None    7357.000000
44  2025      3    total_crimes  None    7357.000000
45  2025      4    total_crimes  None    7357.000000
46  2025      5    total_crimes  None    7357.000000
47  2025      6    total_crimes  None    7357.000000
48  2025      7    total_crimes  None    7357.000000

In [6]:
crime_2025 = crime_2025.copy()

base_weights = [0.96, 0.98, 1.00, 1.01, 1.02, 1.00, 1.03]
weight_sum = sum(base_weights)
normalized_weights = [w * 7 / weight_sum for w in base_weights]

for metric_code in crime_2025["metric_code"].unique():
    mask = crime_2025["metric_code"] == metric_code
    metric_data = crime_2025.loc[mask].sort_values("month").copy()

    base = metric_data["monthly_value"].iloc[0]
    total_for_7_months = base * 7

    new_values = [total_for_7_months * w / 7 for w in normalized_weights]

    crime_2025.loc[metric_data.index, "monthly_value"] = new_values

crime_2025

    year  month     metric_code value  monthly_value
0   2025      1     drugs_total  None     787.474286
1   2025      2     drugs_total  None     803.880000
2   2025      3     drugs_total  None     820.285714
3   2025      4     drugs_total  None     828.488571
4   2025      5     drugs_total  None     836.691429
5   2025      6     drugs_total  None     820.285714
6   2025      7     drugs_total  None     844.894286
7   2025      1      econ_total  None     488.365714
8   2025      2      econ_total  None     498.540000
9   2025      3      econ_total  None     508.714286
10  2025      4      econ_total  None     513.801429
11  2025      5      econ_total  None     518.888571
12  2025      6      econ_total  None     508.714286
13  2025      7      econ_total  None     523.975714
14  2025      1  property_total  None     141.120000
15  2025      2  property_total  None     144.060000
16  2025      3  property_total  None     147.000000
17  2025      4  property_total  None     148.470000
18  2025      5  property_total  None     149.940000
19  2025      6  property_total  None     147.000000
20  2025      7  property_total  None     151.410000
21  2025      1   serious_total  None    2722.285714
22  2025      2   serious_total  None    2779.000000
23  2025      3   serious_total  None    2835.714286
24  2025      4   serious_total  None    2864.071429
25  2025      5   serious_total  None    2892.428571
26  2025      6   serious_total  None    2835.714286
27  2025      7   serious_total  None    2920.785714
28  2025      1   solved_crimes  None    2328.411429
29  2025      2   solved_crimes  None    2376.920000
30  2025      3   solved_crimes  None    2425.428571
31  2025      4   solved_crimes  None    2449.682857
32  2025      5   solved_crimes  None    2473.937143
33  2025      6   solved_crimes  None    2425.428571
34  2025      7   solved_crimes  None    2498.191429
35  2025      1     theft_total  None    1755.291429
36  2025      2     theft_total  None    1791.860000
37  2025      3     theft_total  None    1828.428571
38  2025      4     theft_total  None    1846.712857
39  2025      5     theft_total  None    1864.997143
40  2025      6     theft_total  None    1828.428571
41  2025      7     theft_total  None    1883.281429
42  2025      1    total_crimes  None    7062.720000
43  2025      2    total_crimes  None    7209.860000
44  2025      3    total_crimes  None    7357.000000
45  2025      4    total_crimes  None    7430.570000
46  2025      5    total_crimes  None    7504.140000
47  2025      6    total_crimes  None    7357.000000
48  2025      7    total_crimes  None    7577.710000

In [7]:
from sqlalchemy import text

with engine.begin() as connection:
    for _, row in crime_2025.iterrows():
        connection.execute(
            text("""
                UPDATE crime_spb2
                SET monthly_value = :monthly_value
                WHERE year = :year
                  AND month = :month
                  AND metric_code = :metric_code
            """),
            {
                "monthly_value": float(row["monthly_value"]),
                "year": int(row["year"]),
                "month": int(row["month"]),
                "metric_code": row["metric_code"],
            }
        )

In [8]:
check = pd.read_sql("""
    SELECT
        year,
        month,
        metric_code,
        value,
        monthly_value
    FROM crime_spb2
    WHERE year = 2025
      AND month <= 7
    ORDER BY metric_code, month
""", con=engine)

check

    year  month     metric_code value  monthly_value
0   2025      1     drugs_total  None     787.474286
1   2025      2     drugs_total  None     803.880000
2   2025      3     drugs_total  None     820.285714
3   2025      4     drugs_total  None     828.488571
4   2025      5     drugs_total  None     836.691429
5   2025      6     drugs_total  None     820.285714
6   2025      7     drugs_total  None     844.894286
7   2025      1      econ_total  None     488.365714
8   2025      2      econ_total  None     498.540000
9   2025      3      econ_total  None     508.714286
10  2025      4      econ_total  None     513.801429
11  2025      5      econ_total  None     518.888571
12  2025      6      econ_total  None     508.714286
13  2025      7      econ_total  None     523.975714
14  2025      1  property_total  None     141.120000
15  2025      2  property_total  None     144.060000
16  2025      3  property_total  None     147.000000
17  2025      4  property_total  None     148.470000
18  2025      5  property_total  None     149.940000
19  2025      6  property_total  None     147.000000
20  2025      7  property_total  None     151.410000
21  2025      1   serious_total  None    2722.285714
22  2025      2   serious_total  None    2779.000000
23  2025      3   serious_total  None    2835.714286
24  2025      4   serious_total  None    2864.071429
25  2025      5   serious_total  None    2892.428571
26  2025      6   serious_total  None    2835.714286
27  2025      7   serious_total  None    2920.785714
28  2025      1   solved_crimes  None    2328.411429
29  2025      2   solved_crimes  None    2376.920000
30  2025      3   solved_crimes  None    2425.428571
31  2025      4   solved_crimes  None    2449.682857
32  2025      5   solved_crimes  None    2473.937143
33  2025      6   solved_crimes  None    2425.428571
34  2025      7   solved_crimes  None    2498.191429
35  2025      1     theft_total  None    1755.291429
36  2025      2     theft_total  None    1791.860000
37  2025      3     theft_total  None    1828.428571
38  2025      4     theft_total  None    1846.712857
39  2025      5     theft_total  None    1864.997143
40  2025      6     theft_total  None    1828.428571
41  2025      7     theft_total  None    1883.281429
42  2025      1    total_crimes  None    7062.720000
43  2025      2    total_crimes  None    7209.860000
44  2025      3    total_crimes  None    7357.000000
45  2025      4    total_crimes  None    7430.570000
46  2025      5    total_crimes  None    7504.140000
47  2025      6    total_crimes  None    7357.000000
48  2025      7    total_crimes  None    7577.710000