In [26]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:0000@localhost:5432/crime_spb"
)

In [28]:
problem = pd.read_sql("SELECT * FROM problem_crime_spb", engine)

problem.shape

(184, 20)

In [29]:
problem.columns.tolist()

['group_name',
 'indicator_id',
 'indicator_name',
 'unit',
 'region_name',
 'source',
 'segment',
 'show_flag',
 'y2014',
 'y2015',
 'y2016',
 'y2017',
 'y2018',
 'y2019',
 'y2020',
 'y2021',
 'y2022',
 'y2023',
 'y2024',
 'description']

In [30]:
problem.head()

,group_name,indicator_id,indicator_name,unit,region_name,source,segment,show_flag,y2014,y2015,y2016,y2017,y2018,y2019,y2020,y2021,y2022,y2023,y2024,description
0,Рейтинг,97328,Оценка масштаба проблемы (рейтинг А-Е),,Санкт-Петербург,,,,B,B,B,A,A,A,B,B,A,A,B,А — низкая выраженность проблемы\\nB — проблем...
1,Рейтинг,97329,Оценка масштаба проблемы (рейтинг А-Е),,Санкт-Петербург,,,,B,B,B,A,A,A,B,B,A,A,B,А — низкая выраженность проблемы\\nB — проблем...
2,Масштабы,,,случай,Санкт-Петербург,,,,"18,8","0,0","13,9","2,0","12,4","0,5","11,0",н/д,"9,6596",н/д,н/д,
3,Масштабы,97231,Потерпевшие от преступлений,человек,Санкт-Петербург,,потерпевших,всего,32948,30717,29210,30163,29783,29 005,40334,40269,40133,42232,43771,Потерпевшие: количество потерпевших - физическ...
4,Масштабы,97232,Потерпевшие от преступлений,чел./100000,Санкт-Петербург,,потерпевших,на 100 000 населения,642,592,559,571,556,539,747,748,746,754,782,Потерпевшие: количество потерпевших - физическ...

In [31]:
year_cols = [c for c in problem.columns if c.startswith("y20")]

problem_long = (
    problem
    .melt(
        id_vars=[
            "group_name",
            "indicator_id",
            "indicator_name",
            "unit",
            "region_name",
            "source",
            "segment",
            "show_flag",
            "description",
        ],
        value_vars=year_cols,
        var_name="year_col",
        value_name="value",
    )
)

problem_long["year"] = problem_long["year_col"].str[1:].astype(int)
problem_long = problem_long.drop(columns=["year_col"])

In [42]:
problem_long.head(10)

,group_name,indicator_id,indicator_name,unit,region_name,source,segment,show_flag,description,value,year
0,Рейтинг,97328,Оценка масштаба проблемы (рейтинг А-Е),,Санкт-Петербург,,,,А — низкая выраженность проблемы\\nB — проблем...,B,2014
1,Рейтинг,97329,Оценка масштаба проблемы (рейтинг А-Е),,Санкт-Петербург,,,,А — низкая выраженность проблемы\\nB — проблем...,B,2014
2,Масштабы,,,случай,Санкт-Петербург,,,,,"18,8",2014
3,Масштабы,97231,Потерпевшие от преступлений,человек,Санкт-Петербург,,потерпевших,всего,Потерпевшие: количество потерпевших - физическ...,32948,2014
4,Масштабы,97232,Потерпевшие от преступлений,чел./100000,Санкт-Петербург,,потерпевших,на 100 000 населения,Потерпевшие: количество потерпевших - физическ...,642,2014
5,Масштабы,97233,Потерпевшие от преступлений,случай,Санкт-Петербург,,преступлений,всего,Потерпевшие: количество потерпевших - физическ...,56463,2014
6,Масштабы,97234,Потерпевшие от преступлений,случай,Санкт-Петербург,,преступлений,на 100 000 населения,Потерпевшие: количество потерпевших - физическ...,"1100,2",2014
7,Масштабы,97235,"Потерпевшие - мужчины, женщины и несовершеннол...",человек,Санкт-Петербург,,мужчины,всего человек,,17388,2014
8,Масштабы,97236,"Потерпевшие - мужчины, женщины и несовершеннол...",человек,Санкт-Петербург,,женщины,всего человек,Источник: форма 3-ЕГС \Сведения о зарегистриро...,15560,2014
9,Масштабы,97237,"Потерпевшие - мужчины, женщины и несовершеннол...",человек,Санкт-Петербург,,несовершеннолетние,всего человек,Источник: форма 3-ЕГС \Сведения о зарегистриро...,1127,2014

In [43]:
problem_long.dtypes

group_name        object
indicator_id      object
indicator_name    object
unit              object
region_name       object
source            object
segment           object
show_flag         object
description       object
value             object
year               int64
dtype: object

In [44]:
problem_long["indicator_id"] = pd.to_numeric(
    problem_long["indicator_id"], 
    errors="coerce"
)

In [45]:
problem_long["value"] = (
    problem_long["value"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .str.replace(" ", "", regex=False)
    .replace(["н/д", "NaN", ""], None)
)

In [46]:
problem_long["value"] = pd.to_numeric(
    problem_long["value"], 
    errors="coerce"
)

In [47]:
problem_long.dtypes

group_name         object
indicator_id      float64
indicator_name     object
unit               object
region_name        object
source             object
segment            object
show_flag          object
description        object
value             float64
year                int64
dtype: object

In [48]:
problem_long[["indicator_id", "value", "year"]].head(10)

   indicator_id    value  year
0       97328.0      NaN  2014
1       97329.0      NaN  2014
2           NaN     18.8  2014
3       97231.0  32948.0  2014
4       97232.0    642.0  2014
5       97233.0  56463.0  2014
6       97234.0   1100.2  2014
7       97235.0  17388.0  2014
8       97236.0  15560.0  2014
9       97237.0   1127.0  2014

In [49]:
kpi1_victims_rate = (
    problem_long[problem_long["indicator_id"] == 97232]
    .loc[:, ["year", "value"]]
    .assign(
        kpi_code="victims_rate_total",
        kpi_name="Потерпевшие от преступлений, всего (чел./100000)",
        unit="persons_per_100k",
        sex=None,
        crime_type=None,
        rank=None,
    )
)

print("KPI 1 shape:", kpi1_victims_rate.shape)
kpi1_victims_rate.sort_values("year")

KPI 1 shape: (22, 8)

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
4,2014,642.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
98,2014,1110.6,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
188,2015,592.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
282,2015,1161.6,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
372,2016,559.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
466,2016,1053.8,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
556,2017,571.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
650,2017,965.5,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
740,2018,556.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
834,2018,909.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1018,2019,933.2,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
924,2019,539.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1108,2020,747.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1202,2020,938.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1292,2021,748.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1386,2021,912.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1476,2022,746.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1570,2022,852.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1660,2023,754.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1754,2023,838.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1844,2024,782.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1938,2024,808.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None

In [50]:
problem_long[problem_long["indicator_id"] == 97232][
    ["indicator_name", "unit", "source", "segment", "show_flag", "year", "value"]
].sort_values("year")

,indicator_name,unit,source,segment,show_flag,year,value
4,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2014,642.0
98,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2014,1110.6
188,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2015,592.0
282,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2015,1161.6
372,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2016,559.0
466,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2016,1053.8
556,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2017,571.0
650,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2017,965.5
740,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2018,556.0
834,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2018,909.0
1018,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2019,933.2
924,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2019,539.0
1108,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2020,747.0
1202,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2020,938.0
1292,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2021,748.0
1386,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2021,912.0
1476,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2022,746.0
1570,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2022,852.0
1660,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2023,754.0
1754,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2023,838.0
1844,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2024,782.0
1938,Потерпевшие от преступлений,чел./100000,,потерпевших,на 100 000 населения,2024,808.0

In [51]:
problem_long[problem_long["indicator_id"] == 97232][
    ["group_name", "region_name", "segment", "year", "value"]
].sort_values("year")

     group_name           region_name      segment  year   value
4      Масштабы       Санкт-Петербург  потерпевших  2014   642.0
98     Масштабы  Российская Федерация  потерпевших  2014  1110.6
188    Масштабы       Санкт-Петербург  потерпевших  2015   592.0
282    Масштабы  Российская Федерация  потерпевших  2015  1161.6
372    Масштабы       Санкт-Петербург  потерпевших  2016   559.0
466    Масштабы  Российская Федерация  потерпевших  2016  1053.8
556    Масштабы       Санкт-Петербург  потерпевших  2017   571.0
650    Масштабы  Российская Федерация  потерпевших  2017   965.5
740    Масштабы       Санкт-Петербург  потерпевших  2018   556.0
834    Масштабы  Российская Федерация  потерпевших  2018   909.0
1018   Масштабы  Российская Федерация  потерпевших  2019   933.2
924    Масштабы       Санкт-Петербург  потерпевших  2019   539.0
1108   Масштабы       Санкт-Петербург  потерпевших  2020   747.0
1202   Масштабы  Российская Федерация  потерпевших  2020   938.0
1292   Масштабы       Санкт-Петербург  потерпевших  2021   748.0
1386   Масштабы  Российская Федерация  потерпевших  2021   912.0
1476   Масштабы       Санкт-Петербург  потерпевших  2022   746.0
1570   Масштабы  Российская Федерация  потерпевших  2022   852.0
1660   Масштабы       Санкт-Петербург  потерпевших  2023   754.0
1754   Масштабы  Российская Федерация  потерпевших  2023   838.0
1844   Масштабы       Санкт-Петербург  потерпевших  2024   782.0
1938   Масштабы  Российская Федерация  потерпевших  2024   808.0

In [52]:
kpi1_victims_rate = (
    problem_long[
        (problem_long["indicator_id"] == 97232)
        & (problem_long["region_name"] == "Санкт-Петербург")
    ]
    .loc[:, ["year", "value"]]
    .assign(
        kpi_code="victims_rate_total",
        kpi_name="Потерпевшие от преступлений, всего (чел./100000)",
        unit="persons_per_100k",
        sex=None,
        crime_type=None,
        rank=None,
    )
)

print("KPI 1 shape:", kpi1_victims_rate.shape)
kpi1_victims_rate.sort_values("year")

KPI 1 shape: (11, 8)

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
4,2014,642.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
188,2015,592.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
372,2016,559.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
556,2017,571.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
740,2018,556.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
924,2019,539.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1108,2020,747.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1292,2021,748.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1476,2022,746.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1660,2023,754.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1844,2024,782.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None

In [53]:
kpi2_victims_total = (
    problem_long[
        (problem_long["indicator_id"] == 97231)
        & (problem_long["region_name"] == "Санкт-Петербург")
    ]
    .loc[:, ["year", "value"]]
    .assign(
        kpi_code="victims_total",
        kpi_name="Потерпевшие от преступлений, всего (человек)",
        unit="persons",
        sex=None,
        crime_type=None,
        rank=None,
    )
)

print("KPI 2 shape:", kpi2_victims_total.shape)
kpi2_victims_total.sort_values("year")

KPI 2 shape: (11, 8)

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
3,2014,32948.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
187,2015,30717.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
371,2016,29210.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
555,2017,30163.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
739,2018,29783.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
923,2019,NaN,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
1107,2020,40334.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
1291,2021,40269.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
1475,2022,40133.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
1659,2023,42232.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None
1843,2024,43771.0,victims_total,"Потерпевшие от преступлений, всего (человек)",persons,None,None,None

In [54]:
mask_kpi3 = problem_long["indicator_name"].str.contains(
    "погибли", case=False, na=False
) | problem_long["indicator_name"].str.contains(
    "тяжкий вред", case=False, na=False
)

problem_long[mask_kpi3][
    ["indicator_id", "indicator_name", "unit", "region_name", "source", "segment"]
].drop_duplicates()

,indicator_id,indicator_name,unit,region_name,source,segment
13,97241.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,погибло
14,97242.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,тяжкий вред здоровью
15,97243.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,убито
16,97244.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Санкт-Петербург,,погибло
18,97245.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Санкт-Петербург,,тяжкий вред здоровью
19,97246.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Санкт-Петербург,,убито
20,97247.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,погибшие от насильственных преступлений
21,97248.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,погибшие от насильственных преступлений
22,97249.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Санкт-Петербург,,
23,97250.0,Потерпевшие: погибли и тяжкий вред здоровью (н...,чел./100000,Санкт-Петербург,,
107,97241.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,погибло
108,97242.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,тяжкий вред здоровью
109,97243.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,убито
111,97244.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Российская Федерация,,погибло
112,97245.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Российская Федерация,,тяжкий вред здоровью
113,97246.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,Российская Федерация,,убито
114,97247.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,погибшие от насильственных преступлений
115,97248.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,погибшие от насильственных преступлений
117,97249.0,Потерпевшие: погибли и тяжкий вред здоровью,человек,Российская Федерация,,
118,97250.0,Потерпевшие: погибли и тяжкий вред здоровью (н...,чел./100000,Российская Федерация,,

In [55]:
problem_long[
    problem_long["indicator_id"].isin([97244, 97245, 97246, 97250])
][["indicator_id", "indicator_name", "unit", "segment", "description"]].drop_duplicates()

,indicator_id,indicator_name,unit,segment,description
16,97244.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,погибло,Источник: форма 3-ЕГС \Сведения о зарегистриро...
18,97245.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,тяжкий вред здоровью,Источник: форма 3-ЕГС \Сведения о зарегистриро...
19,97246.0,Потерпевшие: погибли и тяжкий вред здоровью,чел./100000,убито,Источник: форма 3-ЕГС \Сведения о зарегистриро...
23,97250.0,Потерпевшие: погибли и тяжкий вред здоровью (н...,чел./100000,,Данные статистического наблюдения по форме 3-Е...

In [56]:
kpi3_serious_rate = (
    problem_long[
        (problem_long["indicator_id"] == 97250)
        & (problem_long["region_name"] == "Санкт-Петербург")
    ]
    .loc[:, ["year", "value"]]
    .assign(
        kpi_code="victims_serious_rate",
        kpi_name="Погибли и тяжкий вред здоровью (чел./100000)",
        unit="persons_per_100k",
        sex=None,
        crime_type=None,
        rank=None,
    )
)

print("KPI 3 shape:", kpi3_serious_rate.shape)
kpi3_serious_rate.sort_values("year")

KPI 3 shape: (11, 8)

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
23,2014,20.5,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
207,2015,28.6,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
391,2016,25.9,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
575,2017,25.5,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
759,2018,25.7,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
943,2019,22.5,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
1127,2020,22.4,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
1311,2021,22.6,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
1495,2022,19.4,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
1679,2023,18.6,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None
1863,2024,19.4,victims_serious_rate,Погибли и тяжкий вред здоровью (чел./100000),persons_per_100k,None,None,None

In [57]:
problem_long[
    problem_long["indicator_name"].str.contains(
        "изнасил", case=False, na=False
    )
][["indicator_id", "indicator_name"]].drop_duplicates()

    indicator_id                              indicator_name
24       97251.0  Изнасилование и покушение на изнасилование
25       97252.0  Изнасилование и покушение на изнасилование

In [58]:
problem_long[
    problem_long["indicator_id"].isin([97251.0, 97252.0])
][["indicator_id", "indicator_name", "unit"]].drop_duplicates()

    indicator_id                              indicator_name    unit
24       97251.0  Изнасилование и покушение на изнасилование  случай
25       97252.0  Изнасилование и покушение на изнасилование  случай

In [59]:
kpi4_rape_cases = (
    problem_long[
        (problem_long["indicator_id"] == 97251)
        & (problem_long["region_name"] == "Санкт-Петербург")
    ]
    .loc[:, ["year", "value"]]
    .assign(
        kpi_code="rape_attempts_cases",
        kpi_name="Изнасилование и покушение на изнасилование (случай)",
        unit="cases",
        sex=None,
        crime_type=None,
        rank=None,
    )
)

print("KPI 4 shape:", kpi4_rape_cases.shape)
kpi4_rape_cases.sort_values("year")

KPI 4 shape: (11, 8)

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
24,2014,NaN,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
208,2015,NaN,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
392,2016,69.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
576,2017,51.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
760,2018,68.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
944,2019,60.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
1128,2020,42.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
1312,2021,68.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
1496,2022,56.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
1680,2023,51.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None
1864,2024,74.0,rape_attempts_cases,Изнасилование и покушение на изнасилование (сл...,cases,None,None,None

In [61]:
mask_cyber_core = (
    problem_long["indicator_name"].str.contains("совершенн", case=False, na=False)
    & problem_long["indicator_name"].str.contains("использован", case=False, na=False)
    & ~problem_long["indicator_name"].str.contains("раскрываемость", case=False, na=False)
)

cyber_core = problem_long.loc[
    mask_cyber_core,
    ["indicator_id", "indicator_name", "unit"]
].drop_duplicates().sort_values(["indicator_name", "indicator_id"])

cyber_core

Empty DataFrame
Columns: [indicator_id, indicator_name, unit]
Index: []

In [62]:
mask_comp = problem_long["indicator_name"].str.contains(
    "компьютерн", case=False, na=False
)

cyber_comp = problem_long.loc[
    mask_comp,
    ["indicator_id", "indicator_name", "unit"]
].drop_duplicates().sort_values(["indicator_name", "indicator_id"])

cyber_comp

    indicator_id                                     indicator_name     unit
75       97302.0  Раскрываемость преступлений, совершенных c исп...  усл.ед.
76       97303.0  Раскрываемость преступлений, совершенных c исп...  усл.ед.
77       97304.0  Раскрываемость преступлений, совершенных c исп...  усл.ед.

По киберпреступлениям есть только раскрываемость, а самих данных нет;
Итого, оставляем 4 KPI

In [65]:
kpi_all = pd.concat(
    [
        kpi1_victims_rate,
        kpi2_victims_total,
        kpi3_serious_rate,
        kpi4_rape_cases,
    ],
    ignore_index=True,
)

kpi_all.shape

(44, 8)

In [66]:
kpi_all.head()

,year,value,kpi_code,kpi_name,unit,sex,crime_type,rank
0,2014,642.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
1,2015,592.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
2,2016,559.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
3,2017,571.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None
4,2018,556.0,victims_rate_total,"Потерпевшие от преступлений, всего (чел./100000)",persons_per_100k,None,None,None

In [67]:
kpi_all["kpi_code"].value_counts()

kpi_code
victims_rate_total      11
victims_total           11
victims_serious_rate    11
rape_attempts_cases     11
Name: count, dtype: int64

In [68]:
kpi_all.groupby("kpi_code")["year"].nunique()

kpi_code
rape_attempts_cases     11
victims_rate_total      11
victims_serious_rate    11
victims_total           11
Name: year, dtype: int64

In [69]:
kpi_all.isna().sum()

year           0
value          3
kpi_code       0
kpi_name       0
unit           0
sex           44
crime_type    44
rank          44
dtype: int64

In [78]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:0000@localhost:5432/crime_spb"
)

In [79]:
kpi_all["year"] = kpi_all["year"].astype(int)

In [80]:
kpi_all.to_sql(
    "kpi_crime_spb_2ds",
    engine,
    if_exists="append",
    index=False,
)

44

In [82]:
import pandas as pd

check_df = pd.read_sql(
    "SELECT kpi_code, COUNT(*) AS n FROM kpi_crime_spb_2ds GROUP BY kpi_code ORDER BY kpi_code;",
    engine,
)
check_df

               kpi_code   n
0   rape_attempts_cases  11
1    victims_rate_total  11
2  victims_serious_rate  11
3         victims_total  11